export const DEFAULTS = {
    project_name: 'Modular-Multi-Loader-Template',
    project_version: '1.0.0-BETA.1',
    project_group: 'com.example',
    project_title: 'Modular-Multi-Loader-Template',
    project_id: 'Modular_Multi_Loader_Template',
    project_author: '',
    project_credits: '',
    project_description: '',
    project_license: 'MIT',
    minecraft_version: '1.21.1',
    pack_format_version: '48',
    minecraft_version_range: '[1.21, 1.22)',
    neo_form_version: '1.21-20240613.152323',
    parchment_minecraft: '1.21.1',
    parchment_version: '2024.11.17',
    fabric_version: '0.115.0+1.21.1',
    fabric_loader_version: '0.16.10',
    forge_version: '52.0.53',
    forge_loader_version_range: '[51,)',
    neoforge_version: '21.1.125',
    neoforge_loader_version_range: '[1,)',
    java_version: '21',
    gradle_version: 'v8.12.1',
};